In [6]:
import numpy as np
print(np.__version__)


2.2.4


In [6]:
import numpy as np
print(np.__version__)


2.2.4


In [14]:
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [15]:
import numpy as np

arr = np.array(40)   
print(arr)



40


In [16]:
arr = np.array([[1, 2], [3, 4]])
print(arr)



[[1 2]
 [3 4]]


In [17]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
import numpy as np
arr = np.array(5)   
print(arr)
print("Dimensions:", arr.ndim)

5
Dimensions: 0


In [25]:
import numpy as np
arr0 = np.array(40)   
print(arr0.ndim)
arr1= np.array((1,2,3,4,5))
print(arr1.ndim)
arr2= np.array([[1, 2], [3, 4]])
print(arr2.ndim)
arr3= np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3.ndim)

0
1
2
3
