In [1]:
import numpy as np
a= np.array([1,2,3,4],ndmin=5)
print(a)
print("No of dimensions:",a.ndim)

[[[[[1 2 3 4]]]]]
No of dimensions: 5


In [2]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0,1])
b=np.array([[[1,2,3,4],[5,6,7,8]],[[4,5,6,7],[3,5,8,9]]])
print(b[0,1,2])

2
7


In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[1:5])
print(a[4:])
print(a[:4])
print(a[-3:-1])
print(a[1:5:2])
print(a[::2])
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b[1,1:3])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
[6 7]


In [4]:
import numpy as np
td=np.array([5,10,15],dtype="timedelta64[D]")
print(td)
print(td.dtype)

[ 5 10 15]
timedelta64[D]


In [5]:
import numpy as np
a=np.array(["a","ab","abc"])
print(a)
print(a.dtype)

['a' 'ab' 'abc']
<U3


In [6]:
import numpy as np
a=np.array(["a","ab","abc"],dtype='S')
print(a)
print(a.dtype)

[b'a' b'ab' b'abc']
|S3
